[project]
name = "ejercicio-filtrado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "itk>=5.4.2.post1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
]
